scrape_configs:
  - job_name: spark-node-exporter
    scrape_interval: 10s
    static_configs:
      - targets : ["192.178.1.124:9100"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]